### ISSUE TITLE
Possibly unneeded code

### ISSUE THREAD

**Issue by andyg0808** [mhomami/Tank#4]
I'm not sure that this call is needed:
https://github.com/mhomami/Tank/blob/74e115e25ae04a530c524b3d3756b83eb56cb745/js/script.js#L106

The ["Getting Started" docs](https://pixijs.io/guides/basics/getting-started.html) seem to suggest that the rendering will happen automatically as long as you update the positions (see the "Putting It All Together" section at the end).

**Comment by mhomami** [comment]
I commented this out and it ceases to output any of the sprites to the canvas. The example mentioned in those docs uses PIXI.Application which I understand prepackages a lot of the functions for you. Maybe thats why? I honestly cant remember why I put that line in earlier. I'll need to go over the tutorial videos again to find out the why.

**Comment by andyg0808** [comment]
Ah, sounds totally plausible.
